# Generated by Django 3.2.7 on 2021-11-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providers',
            options={'ordering': ['created']},
        ),
    ]
