# Generated by Django 3.2.7 on 2021-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_test_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.IntegerField(help_text='Time limit (in minutes)'),
        ),
    ]
