# Generated by Django 3.2.7 on 2021-10-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('exams', '0003_auto_20211001_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='certification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.providers'),
        ),
    ]
