# Generated by Django 3.2.7 on 2021-10-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='certification',
        ),
    ]
