# Generated by Django 3.2.7 on 2021-10-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_exam_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='topic',
            field=models.CharField(choices=[('Language', 'Laguages'), ('Computers', 'Computers'), ('Testing', 'Testing'), ('Mathematics', 'Mathematics'), ('Blockchain', 'Blockchain'), ('Scrum', 'Scrum'), ('Hacking', 'Hacking')], max_length=50),
        ),
    ]
