# Generated by Django 3.2.7 on 2021-10-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_exam_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='topic',
            field=models.CharField(choices=[('language', 'laguages'), ('computers', 'computers'), ('testing', 'testing'), ('mathematics', 'mathematics'), ('blockchain', 'blockchain'), ('scrum', 'scrum'), ('hacking', 'hacking')], max_length=20),
        ),
    ]
